# Generated by Django 5.0.6 on 2024-05-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coindata',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
