# Generated by Django 5.0.6 on 2024-05-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_creditrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditrequest',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='remaining_updates',
        ),
    ]
