# Generated by Django 5.0.6 on 2024-05-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_creditrequest_expiration_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditRequest',
        ),
    ]
